 @startuml
'Пользовательский путь при работе с MCS

participant "MCS BE"    as be
participant "Cтудент 1" as s1
participant "Cтудент 2" as s2

autonumber

s1 -> be : Создание канала\n и направления. Частота 45 Гц
s2 -> be : Создание канала\n и направления. Частота 45 Гц

s1 -> be : Нажатие кнопки "Вызов"
be -> be : Поиск абонент(а)(ов)\n с частотой вызывающего
alt Найден абонент с заданной частотой
    be -> s2 : Отображение уведомления о входящем звонке
    alt Пользователь принял звонок
    note across: Открытие канала связи
    s1 -> be : Установление взаимодействия через сервер
    s2 -> be : Установление взаимодействия через сервер
    s2 -> be : Завершение звонка
    note across: Закрытие канала связи
    else Пользователь не принял звонок
    note across: Отображение уведомления об отклонении звонка
    be -> s1 : Пользователь отклонил звонок
    end
else Абонент с заданной частотой не найден
note across: Отображение уведомления об отсутствии абонентов
be -> s1 : Абонент с заданной частотой не найден
end
@enduml