DIRECTION_LIST = 'DIRECTION_LIST'
DIRECTION_EDITOR = 'DIRECTION_EDITOR'
MAIN_SCREEN = 'MAIN_SCREEN'
CHANNEL_LIST = 'CHANNEL_LIST'
CHANNEL_EDITOR = 'CHANNEL_EDITOR'
PPRCH_FREQUENCY_PLAN_LIST = "PPRCH_FREQUENCY_PLAN_LIST"
PPRCH_FREQUENCY_PLAN_EDITOR = "PPRCH_FREQUENCY_PLAN_EDITOR"
FREQUENCY_RANGE_EDITOR = "FREQUENCY_RANGE_EDITOR"
